// vue/src/components/FileTitle.vue
<template>
  <ul class="navbar-nav mr-lg-4 w-100">
    <li class="nav-item d-lg-block w-100 text-body ml-0">
      <h4 ref="inputRef" class="file-title d-inline-block mb-0" :contenteditable="editing" />
      <i v-if="editing" class="mdi mdi-check cur-pointer btn-save-title ml-1" alt="保存" @click="doSave" />
      <i v-if="!editing" class="mdi mdi-pencil cur-pointer btn-edit-title ml-1" alt="修改标题" @click="editing = !editing" />
    </li>
  </ul>
</template>

<script>
export default {
  props: {
    save: {
      type: Function,
      required: true
    }
  },

  data () {
    return {
      editing: false
    }
  },

  computed: {
    file () {
      return this.$store.state.File.current
    }
  },

  methods: {
    /**
     * @param {Event} e
     */
    async doSave (e) {
      e.preventDefault()

      const elm = e.target
      if (elm.dataset.saving) {
        return
      }
      elm.dataset.saving = true

      try {
        const newTitle = this.$refs.inputRef.textContent.trim()

        if (newTitle === this.file.title) {
          return
        }

        await this.save(newTitle)
      } catch (e) {
        alert(e)
      } finally {
        delete elm.dataset.saving
        this.editing = false
      }
    }
  },

  mounted () {
    this.$refs.inputRef.textContent = this.file.title
  },

  updated () {
    if (!this.editing) {
      this.$refs.inputRef.textContent = this.file.title
    }
  }
}
</script>

// react/src/components/FileTitle.js
import React from 'react'
import PropTypes from 'prop-types'

class FileTitle extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      editing: false,
      title: props.file.title
    }

    this.inputRef = React.createRef()
    this.handleStartEditing = this.handleStartEditing.bind(this)
    this.handleSaveTitle = this.handleSaveTitle.bind(this)
  }

  componentDidMount () {
    this.inputRef.current.textContent = this.state.title
  }

  handleStartEditing () {
    this.setState({ editing: true })
    setTimeout(() => this.inputRef.current.focus())
  }

  handleSaveTitle () {
    const cleanUp = () => {
      this.setState({ editing: false })
    }
    this.props.onSave(this.props.file.guid, this.inputRef.current.textContent.trim())
      .then(cleanUp, cleanUp)
  }

  render () {
    const editBtn = this.state.editing
      ? <i className='mdi mdi-check cur-pointer btn-save-title ml-1' alt='保存' onClick={this.handleSaveTitle} />
      : <i className='mdi mdi-pencil cur-pointer btn-edit-title ml-1' alt='修改标题' onClick={this.handleStartEditing} />

    return (
      <ul className='navbar-nav mr-lg-4 w-100'>
        <li className='nav-item d-lg-block w-100 text-body ml-0'>
          <h4 ref={this.inputRef} className='file-title d-inline-block mb-0' contentEditable={this.state.editing} />
          {editBtn}
        </li>
      </ul>
    )
  }
}

FileTitle.propTypes = {
  file: PropTypes.object.isRequired,
  onSave: PropTypes.func.isRequired
}

export default FileTitle
