// vue/src/components/SlideEditor.vue
<template>
  <div class="row d-flex flex-grow-1">
    <div class="col-lg-12 grid-margin stretch-card m-0 flex-column-reverse position-relative">
      <div class="editor-container d-flex flex-grow-1 flex-column" ref="editorRef" />
    </div>
  </div>
</template>

<script>
import ShimoCabinet from 'shimo-sdk-cabinet/dist/slide.min'

export default {
  props: {
    file: {
      type: Object,
      required: true
    }
  },

  mounted () {
    const file = this.file

    this.cabinet = new ShimoCabinet({
      fileGuid: file.guid,
      entrypoint: file.config.entrypoint,
      token: file.config.token,

      container: this.$refs.editorRef
    })
    this.cabinet.render()
      .then(
        () => this.$emit('ready'),
        err => this.$emit('error', err)
      )
  },

  destroyed () {
    if (this.cabinet) {
      this.cabinet.destroy()
    }
  }
}
</script>

// react/src/components/SlideEditor.js
import React from 'react'
import PropTypes from 'prop-types'

import ShimoCabinet from 'shimo-sdk-cabinet/dist/slide.min'

class DocumentEditor extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      ready: false
    }

    this.editorRef = React.createRef()
  }

  componentDidMount () {
    const file = this.props.file

    this.cabinet = new ShimoCabinet({
      fileGuid: file.guid,
      entrypoint: file.config.entrypoint,
      token: file.config.token,

      container: this.editorRef.current
    })
    this.cabinet.render()
      .then(() => {
        if (this.props.onReady) {
          this.props.onReady()
        }
      })
  }

  componentWillUnmount () {
    if (this.cabinet) {
      this.cabinet.destroy()
    }
  }

  render () {
    return (
      <div className='editor-container'>
        <div className='editor-body position-relative d-flex flex-grow-1 justify-content-center'>
          <div className='editor flex-grow-1 w-100 h-100' ref={this.editorRef} />
        </div>
      </div>
    )
  }
}

DocumentEditor.propTypes = {
  file: PropTypes.object.isRequired,
  onReady: PropTypes.func
}

export default DocumentEditor
