// vue/src/components/FileList.vue
<template>
  <div class="row flex-grow-1">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">文件列表</h4>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>文件名</th>
                  <th>GUID</th>
                  <th>创建者</th>
                  <th>创建时间</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                <File
                  v-for="file in files" :key="file.guid" :file="file"
                  :remove-file="removeFile"
                  :export-file="exportFile"
                />
              </tbody>
            </table>
            <div class={paginationClasses}>
              <button v-if="files.length > size" type='button' class="majestic-btn btn-link" onClick="changePage(page + 1)">下一页</button>
              <button v-if="page > 0" type='button' class="majestic-btn btn-link" onClick="changePage(page - 1)">上一页</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import File from './File.vue'

export default {
  components: {
    File
  },

  data () {
    return {
      files: [],
      page: 0,
      size: 20
    }
  },

  methods: {
    changePage (page) {
      return () => {
        this.$store.dispatch('requestFiles', { page, size: this.size })
          .then(
            files => (this.files = files),
            err => alert(err)
          )
      }
    },

    async exportFile (file, toType) {
      try {
        const url = await this.$store.dispatch('exportFile', { file, toType })

        const a = document.createElement('a')
        a.setAttribute('download', file.title)
        a.href = url
        a.click()
      } catch (e) {
        alert(e)
      }
    },

    async removeFile (file) {
      try {
        await this.$store.dispatch('removeFile', file.guid)
        this.files = this.files.filter(f => f.guid !== file.guid)
      } catch (e) {
        alert(e)
      }
    }
  },

  mounted () {
    this.$store.dispatch('requestFiles', { page: this.page, size: this.size })
      .then(
        files => (this.files = files),
        err => alert(err)
      )
  }
}
</script>

<style>

</style>

// react/src/containers/FileList.js
import React from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import PropTypes from 'prop-types'

import { requestFiles, exportFile, removeFile } from '../actions'
import File from '../components/File'

class FileList extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      page: 0,
      size: 20
    }

    this.handleRemove = this.handleRemove.bind(this)
    this.handleExport = this.handleExport.bind(this)
  }

  componentDidMount () {
    this.props.requestFiles(this.state.page, this.state.size)
  }

  async handleRemove (file) {
    await this.props.removeFile(file.guid)
      .catch(err => alert(err))
  }

  async handleExport (file, toType) {
    await this.props.exportFile(file, toType)
      .then(url => {
        const a = document.createElement('a')
        a.setAttribute('download', '')
        a.href = url
        a.click()
      })
      .catch(err => alert(err))
  }

  handleChangePage (page) {
    return () => {
      this.props.requestFiles(page, this.state.size)
        .then(
          () => this.setState({ page }),
          err => alert(err)
        )
    }
  }

  render () {
    const files = this.props.files.map(file => {
      return <File file={file} key={file.guid} onRemove={this.handleRemove} onExport={this.handleExport} />
    })

    const paginationClasses = `d-flex justify-content-between mt-3 flex-row${files.length >= this.state.size ? '-reverse' : ''}`

    return (
      <div className='row flex-grow-1'>
        <div className='col-lg-12 grid-margin stretch-card'>
          <div className='card'>
            <div className='card-body'>
              <h4 className='card-title'>文件列表</h4>
              <div className='table-responsive'>
                <table className='table'>
                  <thead>
                    <tr>
                      <th>文件名</th>
                      <th>GUID</th>
                      <th>创建者</th>
                      <th>创建时间</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {files}
                  </tbody>
                </table>
                <div className={paginationClasses}>
                  {files.length >= this.state.size &&
                    <button type='button' className='majestic-btn btn-link' onClick={this.handleChangePage(this.state.page + 1)}>下一页</button>}
                  {this.state.page > 0 &&
                    <button type='button' className='majestic-btn btn-link' onClick={this.handleChangePage(this.state.page - 1)}>上一页</button>}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

FileList.propTypes = {
  files: PropTypes.array,
  requestFiles: PropTypes.func,
  removeFile: PropTypes.func,
  exportFile: PropTypes.func
}

export default connect(
  (state, ownProps) => ({
    files: state.File.list,
    state,
    ownProps
  }),
  dispatch => ({
    ...bindActionCreators({ requestFiles, exportFile, removeFile }, dispatch)
  })
)(FileList)
